name: Deploy Preview to Firebase Hosting
on:
  pull_request:
    branches-ignore:
      - live-site

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'yarn'

      - run: yarn install

      - name: Build Docs
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run docs:build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SA_VITEPRESS_DOCS }}'
          expires: 7d
